package com.mybatis.cli;

import com.mybatis.CourseSchedule;
import com.mybatis.CourseScheduleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CourseScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    long countByExample(CourseScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int deleteByExample(CourseScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int insert(CourseSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int insertSelective(CourseSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    List<CourseSchedule> selectByExample(CourseScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    CourseSchedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") CourseSchedule record, @Param("example") CourseScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int updateByExample(@Param("record") CourseSchedule record, @Param("example") CourseScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int updateByPrimaryKeySelective(CourseSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int updateByPrimaryKey(CourseSchedule record);
}