package com.mybatis.cli;

import com.mybatis.Favorite;
import com.mybatis.FavoriteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavoriteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	long countByExample(FavoriteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	int deleteByExample(FavoriteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	int insert(Favorite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	int insertSelective(Favorite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	List<Favorite> selectByExample(FavoriteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	Favorite selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Favorite record, @Param("example") FavoriteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	int updateByExample(@Param("record") Favorite record, @Param("example") FavoriteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	int updateByPrimaryKeySelective(Favorite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITES
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	int updateByPrimaryKey(Favorite record);
}