package com.mybatis.cli;

import com.mybatis.FavoriteAnswer;
import com.mybatis.FavoriteAnswerExample;
import com.mybatis.FavoriteAnswerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavoriteAnswerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	long countByExample(FavoriteAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int deleteByExample(FavoriteAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int deleteByPrimaryKey(FavoriteAnswerKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int insert(FavoriteAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int insertSelective(FavoriteAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	List<FavoriteAnswer> selectByExample(FavoriteAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	FavoriteAnswer selectByPrimaryKey(FavoriteAnswerKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int updateByExampleSelective(@Param("record") FavoriteAnswer record,
			@Param("example") FavoriteAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int updateByExample(@Param("record") FavoriteAnswer record, @Param("example") FavoriteAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int updateByPrimaryKeySelective(FavoriteAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.FAVORITE_ANSWER
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int updateByPrimaryKey(FavoriteAnswer record);
}