package com.mybatis.cli;

import com.mybatis.MyFavoriteExample;
import com.mybatis.MyFavoriteKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyFavoriteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.MY_FAVORITES
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	long countByExample(MyFavoriteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.MY_FAVORITES
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	int deleteByExample(MyFavoriteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.MY_FAVORITES
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	int deleteByPrimaryKey(MyFavoriteKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.MY_FAVORITES
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	int insert(MyFavoriteKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.MY_FAVORITES
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	int insertSelective(MyFavoriteKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.MY_FAVORITES
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	List<MyFavoriteKey> selectByExample(MyFavoriteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.MY_FAVORITES
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	int updateByExampleSelective(@Param("record") MyFavoriteKey record, @Param("example") MyFavoriteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.MY_FAVORITES
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	int updateByExample(@Param("record") MyFavoriteKey record, @Param("example") MyFavoriteExample example);
}