package com.mybatis.cli;

import com.mybatis.Question;
import com.mybatis.QuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    long countByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int deleteByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    List<Question> selectByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    Question selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int updateByExample(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.QUESTION
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    int updateByPrimaryKey(Question record);
}