package com.mybatis.cli;

import com.mybatis.TwoDimentionCode;
import com.mybatis.TwoDimentionCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TwoDimentionCodeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	long countByExample(TwoDimentionCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int deleteByExample(TwoDimentionCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int insert(TwoDimentionCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int insertSelective(TwoDimentionCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	List<TwoDimentionCode> selectByExample(TwoDimentionCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	TwoDimentionCode selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TwoDimentionCode record,
			@Param("example") TwoDimentionCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int updateByExample(@Param("record") TwoDimentionCode record, @Param("example") TwoDimentionCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int updateByPrimaryKeySelective(TwoDimentionCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	int updateByPrimaryKey(TwoDimentionCode record);
}