package com.mybatis;

import java.util.Date;

public class Answer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.ANSWERS.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.ANSWERS.QUESTION_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer questionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.ANSWERS.PARENT_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.ANSWERS.DESC
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.ANSWERS.VOTES
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer votes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.ANSWERS.USER_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.ANSWERS.CREDIT_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer creditId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.ANSWERS.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.ANSWERS.ID
	 * @return  the value of PUBLIC.ANSWERS.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.ANSWERS.ID
	 * @param id  the value for PUBLIC.ANSWERS.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.ANSWERS.QUESTION_ID
	 * @return  the value of PUBLIC.ANSWERS.QUESTION_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getQuestionId() {
		return questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.ANSWERS.QUESTION_ID
	 * @param questionId  the value for PUBLIC.ANSWERS.QUESTION_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.ANSWERS.PARENT_ID
	 * @return  the value of PUBLIC.ANSWERS.PARENT_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.ANSWERS.PARENT_ID
	 * @param parentId  the value for PUBLIC.ANSWERS.PARENT_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.ANSWERS.DESC
	 * @return  the value of PUBLIC.ANSWERS.DESC
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.ANSWERS.DESC
	 * @param desc  the value for PUBLIC.ANSWERS.DESC
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.ANSWERS.VOTES
	 * @return  the value of PUBLIC.ANSWERS.VOTES
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getVotes() {
		return votes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.ANSWERS.VOTES
	 * @param votes  the value for PUBLIC.ANSWERS.VOTES
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setVotes(Integer votes) {
		this.votes = votes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.ANSWERS.USER_ID
	 * @return  the value of PUBLIC.ANSWERS.USER_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.ANSWERS.USER_ID
	 * @param userId  the value for PUBLIC.ANSWERS.USER_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.ANSWERS.CREDIT_ID
	 * @return  the value of PUBLIC.ANSWERS.CREDIT_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getCreditId() {
		return creditId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.ANSWERS.CREDIT_ID
	 * @param creditId  the value for PUBLIC.ANSWERS.CREDIT_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setCreditId(Integer creditId) {
		this.creditId = creditId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.ANSWERS.UPDATE_TIME
	 * @return  the value of PUBLIC.ANSWERS.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.ANSWERS.UPDATE_TIME
	 * @param updateTime  the value for PUBLIC.ANSWERS.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}