package com.mybatis;

public class Answer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANSWER.ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANSWER.QUESTION_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANSWER.PARENT_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANSWER.DESC
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANSWER.VOTES
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private Integer votes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANSWER.ANSWER_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private Integer answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ANSWER.USER_OPEN_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private String userOpenId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANSWER.ID
     *
     * @return the value of PUBLIC.ANSWER.ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANSWER.ID
     *
     * @param id the value for PUBLIC.ANSWER.ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANSWER.QUESTION_ID
     *
     * @return the value of PUBLIC.ANSWER.QUESTION_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANSWER.QUESTION_ID
     *
     * @param questionId the value for PUBLIC.ANSWER.QUESTION_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANSWER.PARENT_ID
     *
     * @return the value of PUBLIC.ANSWER.PARENT_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANSWER.PARENT_ID
     *
     * @param parentId the value for PUBLIC.ANSWER.PARENT_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANSWER.DESC
     *
     * @return the value of PUBLIC.ANSWER.DESC
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANSWER.DESC
     *
     * @param desc the value for PUBLIC.ANSWER.DESC
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANSWER.VOTES
     *
     * @return the value of PUBLIC.ANSWER.VOTES
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public Integer getVotes() {
        return votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANSWER.VOTES
     *
     * @param votes the value for PUBLIC.ANSWER.VOTES
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setVotes(Integer votes) {
        this.votes = votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANSWER.ANSWER_ID
     *
     * @return the value of PUBLIC.ANSWER.ANSWER_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANSWER.ANSWER_ID
     *
     * @param answerId the value for PUBLIC.ANSWER.ANSWER_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ANSWER.USER_OPEN_ID
     *
     * @return the value of PUBLIC.ANSWER.USER_OPEN_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public String getUserOpenId() {
        return userOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ANSWER.USER_OPEN_ID
     *
     * @param userOpenId the value for PUBLIC.ANSWER.USER_OPEN_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setUserOpenId(String userOpenId) {
        this.userOpenId = userOpenId;
    }
}