package com.mybatis;

import java.util.Date;

public class CourseSchedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE_SCHEDULE.ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE_SCHEDULE.COURSE_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE_SCHEDULE.INSTRUCTOR_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private String instructorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE_SCHEDULE.start
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private Date start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE_SCHEDULE.end
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private Date end;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE_SCHEDULE.ID
     *
     * @return the value of PUBLIC.COURSE_SCHEDULE.ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE_SCHEDULE.ID
     *
     * @param id the value for PUBLIC.COURSE_SCHEDULE.ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE_SCHEDULE.COURSE_ID
     *
     * @return the value of PUBLIC.COURSE_SCHEDULE.COURSE_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE_SCHEDULE.COURSE_ID
     *
     * @param courseId the value for PUBLIC.COURSE_SCHEDULE.COURSE_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE_SCHEDULE.INSTRUCTOR_ID
     *
     * @return the value of PUBLIC.COURSE_SCHEDULE.INSTRUCTOR_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public String getInstructorId() {
        return instructorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE_SCHEDULE.INSTRUCTOR_ID
     *
     * @param instructorId the value for PUBLIC.COURSE_SCHEDULE.INSTRUCTOR_ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setInstructorId(String instructorId) {
        this.instructorId = instructorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE_SCHEDULE.start
     *
     * @return the value of PUBLIC.COURSE_SCHEDULE.start
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE_SCHEDULE.start
     *
     * @param start the value for PUBLIC.COURSE_SCHEDULE.start
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE_SCHEDULE.end
     *
     * @return the value of PUBLIC.COURSE_SCHEDULE.end
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE_SCHEDULE.end
     *
     * @param end the value for PUBLIC.COURSE_SCHEDULE.end
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setEnd(Date end) {
        this.end = end;
    }
}