package com.mybatis;

import java.util.Date;

public class Course {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSES.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSES.TITLE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSES.DESC
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSES.MEMO
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSES.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSES.CREATOR_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer creatorId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSES.ID
	 * @return  the value of PUBLIC.COURSES.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSES.ID
	 * @param id  the value for PUBLIC.COURSES.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSES.TITLE
	 * @return  the value of PUBLIC.COURSES.TITLE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSES.TITLE
	 * @param title  the value for PUBLIC.COURSES.TITLE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSES.DESC
	 * @return  the value of PUBLIC.COURSES.DESC
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSES.DESC
	 * @param desc  the value for PUBLIC.COURSES.DESC
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSES.MEMO
	 * @return  the value of PUBLIC.COURSES.MEMO
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSES.MEMO
	 * @param memo  the value for PUBLIC.COURSES.MEMO
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSES.UPDATE_TIME
	 * @return  the value of PUBLIC.COURSES.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSES.UPDATE_TIME
	 * @param updateTime  the value for PUBLIC.COURSES.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSES.CREATOR_ID
	 * @return  the value of PUBLIC.COURSES.CREATOR_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getCreatorId() {
		return creatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSES.CREATOR_ID
	 * @param creatorId  the value for PUBLIC.COURSES.CREATOR_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setCreatorId(Integer creatorId) {
		this.creatorId = creatorId;
	}
}