package com.mybatis;

import java.util.Date;

public class CourseSchedule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSE_SCHEDULE.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSE_SCHEDULE.COURSE_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer courseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSE_SCHEDULE.START_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSE_SCHEDULE.END_ENDTIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Date endEndtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSE_SCHEDULE.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Date updateTime;
	


	private String title;
	private String location;
	private String lecturer;
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSE_SCHEDULE.ID
	 * @return  the value of PUBLIC.COURSE_SCHEDULE.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSE_SCHEDULE.ID
	 * @param id  the value for PUBLIC.COURSE_SCHEDULE.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSE_SCHEDULE.COURSE_ID
	 * @return  the value of PUBLIC.COURSE_SCHEDULE.COURSE_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getCourseId() {
		return courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSE_SCHEDULE.COURSE_ID
	 * @param courseId  the value for PUBLIC.COURSE_SCHEDULE.COURSE_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSE_SCHEDULE.START_TIME
	 * @return  the value of PUBLIC.COURSE_SCHEDULE.START_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSE_SCHEDULE.START_TIME
	 * @param startTime  the value for PUBLIC.COURSE_SCHEDULE.START_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSE_SCHEDULE.END_ENDTIME
	 * @return  the value of PUBLIC.COURSE_SCHEDULE.END_ENDTIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Date getEndEndtime() {
		return endEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSE_SCHEDULE.END_ENDTIME
	 * @param endEndtime  the value for PUBLIC.COURSE_SCHEDULE.END_ENDTIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setEndEndtime(Date endEndtime) {
		this.endEndtime = endEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSE_SCHEDULE.UPDATE_TIME
	 * @return  the value of PUBLIC.COURSE_SCHEDULE.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSE_SCHEDULE.UPDATE_TIME
	 * @param updateTime  the value for PUBLIC.COURSE_SCHEDULE.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getLecturer() {
		return lecturer;
	}

	public void setLecturer(String lecturer) {
		this.lecturer = lecturer;
	}

}