package com.mybatis;

public class Course {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSES.ID
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSES.TITLE
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSES.DESC
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.COURSES.MEMO
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	private Integer memo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSES.ID
	 * @return  the value of PUBLIC.COURSES.ID
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSES.ID
	 * @param id  the value for PUBLIC.COURSES.ID
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSES.TITLE
	 * @return  the value of PUBLIC.COURSES.TITLE
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSES.TITLE
	 * @param title  the value for PUBLIC.COURSES.TITLE
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSES.DESC
	 * @return  the value of PUBLIC.COURSES.DESC
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSES.DESC
	 * @param desc  the value for PUBLIC.COURSES.DESC
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.COURSES.MEMO
	 * @return  the value of PUBLIC.COURSES.MEMO
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public Integer getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.COURSES.MEMO
	 * @param memo  the value for PUBLIC.COURSES.MEMO
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public void setMemo(Integer memo) {
		this.memo = memo;
	}
}