package com.mybatis;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CourseScheduleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public CourseScheduleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCourseIdIsNull() {
			addCriterion("COURSE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCourseIdIsNotNull() {
			addCriterion("COURSE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCourseIdEqualTo(Integer value) {
			addCriterion("COURSE_ID =", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdNotEqualTo(Integer value) {
			addCriterion("COURSE_ID <>", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdGreaterThan(Integer value) {
			addCriterion("COURSE_ID >", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("COURSE_ID >=", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdLessThan(Integer value) {
			addCriterion("COURSE_ID <", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdLessThanOrEqualTo(Integer value) {
			addCriterion("COURSE_ID <=", value, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdIn(List<Integer> values) {
			addCriterion("COURSE_ID in", values, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdNotIn(List<Integer> values) {
			addCriterion("COURSE_ID not in", values, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdBetween(Integer value1, Integer value2) {
			addCriterion("COURSE_ID between", value1, value2, "courseId");
			return (Criteria) this;
		}

		public Criteria andCourseIdNotBetween(Integer value1, Integer value2) {
			addCriterion("COURSE_ID not between", value1, value2, "courseId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdIsNull() {
			addCriterion("INSTRUCTOR_ID is null");
			return (Criteria) this;
		}

		public Criteria andInstructorIdIsNotNull() {
			addCriterion("INSTRUCTOR_ID is not null");
			return (Criteria) this;
		}

		public Criteria andInstructorIdEqualTo(String value) {
			addCriterion("INSTRUCTOR_ID =", value, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdNotEqualTo(String value) {
			addCriterion("INSTRUCTOR_ID <>", value, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdGreaterThan(String value) {
			addCriterion("INSTRUCTOR_ID >", value, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdGreaterThanOrEqualTo(String value) {
			addCriterion("INSTRUCTOR_ID >=", value, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdLessThan(String value) {
			addCriterion("INSTRUCTOR_ID <", value, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdLessThanOrEqualTo(String value) {
			addCriterion("INSTRUCTOR_ID <=", value, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdLike(String value) {
			addCriterion("INSTRUCTOR_ID like", value, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdNotLike(String value) {
			addCriterion("INSTRUCTOR_ID not like", value, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdIn(List<String> values) {
			addCriterion("INSTRUCTOR_ID in", values, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdNotIn(List<String> values) {
			addCriterion("INSTRUCTOR_ID not in", values, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdBetween(String value1, String value2) {
			addCriterion("INSTRUCTOR_ID between", value1, value2, "instructorId");
			return (Criteria) this;
		}

		public Criteria andInstructorIdNotBetween(String value1, String value2) {
			addCriterion("INSTRUCTOR_ID not between", value1, value2, "instructorId");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("START_TIME is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("START_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Date value) {
			addCriterion("START_TIME =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Date value) {
			addCriterion("START_TIME <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Date value) {
			addCriterion("START_TIME >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("START_TIME >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Date value) {
			addCriterion("START_TIME <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Date value) {
			addCriterion("START_TIME <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Date> values) {
			addCriterion("START_TIME in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Date> values) {
			addCriterion("START_TIME not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Date value1, Date value2) {
			addCriterion("START_TIME between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Date value1, Date value2) {
			addCriterion("START_TIME not between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeIsNull() {
			addCriterion("END_ENDTIME is null");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeIsNotNull() {
			addCriterion("END_ENDTIME is not null");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeEqualTo(Date value) {
			addCriterion("END_ENDTIME =", value, "endEndtime");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeNotEqualTo(Date value) {
			addCriterion("END_ENDTIME <>", value, "endEndtime");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeGreaterThan(Date value) {
			addCriterion("END_ENDTIME >", value, "endEndtime");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("END_ENDTIME >=", value, "endEndtime");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeLessThan(Date value) {
			addCriterion("END_ENDTIME <", value, "endEndtime");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("END_ENDTIME <=", value, "endEndtime");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeIn(List<Date> values) {
			addCriterion("END_ENDTIME in", values, "endEndtime");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeNotIn(List<Date> values) {
			addCriterion("END_ENDTIME not in", values, "endEndtime");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeBetween(Date value1, Date value2) {
			addCriterion("END_ENDTIME between", value1, value2, "endEndtime");
			return (Criteria) this;
		}

		public Criteria andEndEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("END_ENDTIME not between", value1, value2, "endEndtime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.COURSE_SCHEDULE
	 * @mbg.generated  Fri Nov 24 13:12:07 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUBLIC.COURSE_SCHEDULE
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 20 10:00:46 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}