package com.mybatis;

public class FavoriteAnswer extends FavoriteAnswerKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.FAVORITE_ANSWER.IS_FAVORITE
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	private String isFavorite;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.FAVORITE_ANSWER.IS_FAVORITE
	 * @return  the value of PUBLIC.FAVORITE_ANSWER.IS_FAVORITE
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	public String getIsFavorite() {
		return isFavorite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.FAVORITE_ANSWER.IS_FAVORITE
	 * @param isFavorite  the value for PUBLIC.FAVORITE_ANSWER.IS_FAVORITE
	 * @mbg.generated  Sat Nov 25 21:10:41 CST 2017
	 */
	public void setIsFavorite(String isFavorite) {
		this.isFavorite = isFavorite;
	}
}