package com.mybatis;

import java.util.Date;

public class FavoriteAnswer extends FavoriteAnswerKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.FAVORITE_ANSWER.IS_FAVORITE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private String isFavorite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.FAVORITE_ANSWER.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.FAVORITE_ANSWER.IS_FAVORITE
	 * @return  the value of PUBLIC.FAVORITE_ANSWER.IS_FAVORITE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public String getIsFavorite() {
		return isFavorite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.FAVORITE_ANSWER.IS_FAVORITE
	 * @param isFavorite  the value for PUBLIC.FAVORITE_ANSWER.IS_FAVORITE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setIsFavorite(String isFavorite) {
		this.isFavorite = isFavorite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.FAVORITE_ANSWER.UPDATE_TIME
	 * @return  the value of PUBLIC.FAVORITE_ANSWER.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.FAVORITE_ANSWER.UPDATE_TIME
	 * @param updateTime  the value for PUBLIC.FAVORITE_ANSWER.UPDATE_TIME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}