package com.mybatis;

public class MyFavoriteKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.MY_FAVORITES.OPEN_ID
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.MY_FAVORITES.FAVORITES_ID
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	private Integer favoritesId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.MY_FAVORITES.OPEN_ID
	 * @return  the value of PUBLIC.MY_FAVORITES.OPEN_ID
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.MY_FAVORITES.OPEN_ID
	 * @param openId  the value for PUBLIC.MY_FAVORITES.OPEN_ID
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.MY_FAVORITES.FAVORITES_ID
	 * @return  the value of PUBLIC.MY_FAVORITES.FAVORITES_ID
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public Integer getFavoritesId() {
		return favoritesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.MY_FAVORITES.FAVORITES_ID
	 * @param favoritesId  the value for PUBLIC.MY_FAVORITES.FAVORITES_ID
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public void setFavoritesId(Integer favoritesId) {
		this.favoritesId = favoritesId;
	}
}