package com.mybatis;

import java.util.Date;

public class MyFavorite extends MyFavoriteKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MY_FAVORITES.UPDATE_TIME
     *
     * @mbg.generated Sun Nov 26 15:15:32 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MY_FAVORITES.UPDATE_TIME
     *
     * @return the value of PUBLIC.MY_FAVORITES.UPDATE_TIME
     *
     * @mbg.generated Sun Nov 26 15:15:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MY_FAVORITES.UPDATE_TIME
     *
     * @param updateTime the value for PUBLIC.MY_FAVORITES.UPDATE_TIME
     *
     * @mbg.generated Sun Nov 26 15:15:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}