package com.mybatis;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.QUESTION.ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.QUESTION.DESC
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.QUESTION.OWNER
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    private String owner;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.QUESTION.ID
     *
     * @return the value of PUBLIC.QUESTION.ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.QUESTION.ID
     *
     * @param id the value for PUBLIC.QUESTION.ID
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.QUESTION.DESC
     *
     * @return the value of PUBLIC.QUESTION.DESC
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.QUESTION.DESC
     *
     * @param desc the value for PUBLIC.QUESTION.DESC
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.QUESTION.OWNER
     *
     * @return the value of PUBLIC.QUESTION.OWNER
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.QUESTION.OWNER
     *
     * @param owner the value for PUBLIC.QUESTION.OWNER
     *
     * @mbg.generated Sun Nov 19 12:53:08 CST 2017
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }
}