package com.mybatis;

import java.util.List;

public class Question {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.QUESTIONS.ID
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.QUESTIONS.DESC
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.QUESTIONS.OWNER
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	private String owner;

	private List<Answer> answers;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.QUESTIONS.ID
	 * @return  the value of PUBLIC.QUESTIONS.ID
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.QUESTIONS.ID
	 * @param id  the value for PUBLIC.QUESTIONS.ID
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.QUESTIONS.DESC
	 * @return  the value of PUBLIC.QUESTIONS.DESC
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.QUESTIONS.DESC
	 * @param desc  the value for PUBLIC.QUESTIONS.DESC
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.QUESTIONS.OWNER
	 * @return  the value of PUBLIC.QUESTIONS.OWNER
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.QUESTIONS.OWNER
	 * @param owner  the value for PUBLIC.QUESTIONS.OWNER
	 * @mbg.generated  Mon Nov 20 10:51:13 CST 2017
	 */
	public void setOwner(String owner) {
		this.owner = owner;
	}

    public List<Answer> getAnswers() {
        return answers;
    }

    public void setAnswers(List<Answer> answers) {
        this.answers = answers;
    }
}