package com.mybatis;

public class TwoDimentionCode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.TWO_DIMENTION_CODE.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.TWO_DIMENTION_CODE.SCENE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private String scene;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.TWO_DIMENTION_CODE.FILE_NAME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.TWO_DIMENTION_CODE.OBJECT_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private Integer objectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.TWO_DIMENTION_CODE.WECHAT_CONF
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	private String wechatConf;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.TWO_DIMENTION_CODE.ID
	 * @return  the value of PUBLIC.TWO_DIMENTION_CODE.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.TWO_DIMENTION_CODE.ID
	 * @param id  the value for PUBLIC.TWO_DIMENTION_CODE.ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.TWO_DIMENTION_CODE.SCENE
	 * @return  the value of PUBLIC.TWO_DIMENTION_CODE.SCENE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public String getScene() {
		return scene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.TWO_DIMENTION_CODE.SCENE
	 * @param scene  the value for PUBLIC.TWO_DIMENTION_CODE.SCENE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setScene(String scene) {
		this.scene = scene;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.TWO_DIMENTION_CODE.FILE_NAME
	 * @return  the value of PUBLIC.TWO_DIMENTION_CODE.FILE_NAME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.TWO_DIMENTION_CODE.FILE_NAME
	 * @param fileName  the value for PUBLIC.TWO_DIMENTION_CODE.FILE_NAME
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.TWO_DIMENTION_CODE.OBJECT_ID
	 * @return  the value of PUBLIC.TWO_DIMENTION_CODE.OBJECT_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Integer getObjectId() {
		return objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.TWO_DIMENTION_CODE.OBJECT_ID
	 * @param objectId  the value for PUBLIC.TWO_DIMENTION_CODE.OBJECT_ID
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.TWO_DIMENTION_CODE.WECHAT_CONF
	 * @return  the value of PUBLIC.TWO_DIMENTION_CODE.WECHAT_CONF
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public String getWechatConf() {
		return wechatConf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.TWO_DIMENTION_CODE.WECHAT_CONF
	 * @param wechatConf  the value for PUBLIC.TWO_DIMENTION_CODE.WECHAT_CONF
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setWechatConf(String wechatConf) {
		this.wechatConf = wechatConf;
	}
}