package com.mybatis;

import java.util.ArrayList;
import java.util.List;

public class TwoDimentionCodeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public TwoDimentionCodeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSceneIsNull() {
			addCriterion("SCENE is null");
			return (Criteria) this;
		}

		public Criteria andSceneIsNotNull() {
			addCriterion("SCENE is not null");
			return (Criteria) this;
		}

		public Criteria andSceneEqualTo(String value) {
			addCriterion("SCENE =", value, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneNotEqualTo(String value) {
			addCriterion("SCENE <>", value, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneGreaterThan(String value) {
			addCriterion("SCENE >", value, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneGreaterThanOrEqualTo(String value) {
			addCriterion("SCENE >=", value, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneLessThan(String value) {
			addCriterion("SCENE <", value, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneLessThanOrEqualTo(String value) {
			addCriterion("SCENE <=", value, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneLike(String value) {
			addCriterion("SCENE like", value, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneNotLike(String value) {
			addCriterion("SCENE not like", value, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneIn(List<String> values) {
			addCriterion("SCENE in", values, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneNotIn(List<String> values) {
			addCriterion("SCENE not in", values, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneBetween(String value1, String value2) {
			addCriterion("SCENE between", value1, value2, "scene");
			return (Criteria) this;
		}

		public Criteria andSceneNotBetween(String value1, String value2) {
			addCriterion("SCENE not between", value1, value2, "scene");
			return (Criteria) this;
		}

		public Criteria andFileNameIsNull() {
			addCriterion("FILE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andFileNameIsNotNull() {
			addCriterion("FILE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andFileNameEqualTo(String value) {
			addCriterion("FILE_NAME =", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotEqualTo(String value) {
			addCriterion("FILE_NAME <>", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameGreaterThan(String value) {
			addCriterion("FILE_NAME >", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameGreaterThanOrEqualTo(String value) {
			addCriterion("FILE_NAME >=", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLessThan(String value) {
			addCriterion("FILE_NAME <", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLessThanOrEqualTo(String value) {
			addCriterion("FILE_NAME <=", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameLike(String value) {
			addCriterion("FILE_NAME like", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotLike(String value) {
			addCriterion("FILE_NAME not like", value, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameIn(List<String> values) {
			addCriterion("FILE_NAME in", values, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotIn(List<String> values) {
			addCriterion("FILE_NAME not in", values, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameBetween(String value1, String value2) {
			addCriterion("FILE_NAME between", value1, value2, "fileName");
			return (Criteria) this;
		}

		public Criteria andFileNameNotBetween(String value1, String value2) {
			addCriterion("FILE_NAME not between", value1, value2, "fileName");
			return (Criteria) this;
		}

		public Criteria andObjectIdIsNull() {
			addCriterion("OBJECT_ID is null");
			return (Criteria) this;
		}

		public Criteria andObjectIdIsNotNull() {
			addCriterion("OBJECT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andObjectIdEqualTo(Integer value) {
			addCriterion("OBJECT_ID =", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotEqualTo(Integer value) {
			addCriterion("OBJECT_ID <>", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdGreaterThan(Integer value) {
			addCriterion("OBJECT_ID >", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("OBJECT_ID >=", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdLessThan(Integer value) {
			addCriterion("OBJECT_ID <", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdLessThanOrEqualTo(Integer value) {
			addCriterion("OBJECT_ID <=", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdIn(List<Integer> values) {
			addCriterion("OBJECT_ID in", values, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotIn(List<Integer> values) {
			addCriterion("OBJECT_ID not in", values, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdBetween(Integer value1, Integer value2) {
			addCriterion("OBJECT_ID between", value1, value2, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotBetween(Integer value1, Integer value2) {
			addCriterion("OBJECT_ID not between", value1, value2, "objectId");
			return (Criteria) this;
		}

		public Criteria andWechatConfIsNull() {
			addCriterion("WECHAT_CONF is null");
			return (Criteria) this;
		}

		public Criteria andWechatConfIsNotNull() {
			addCriterion("WECHAT_CONF is not null");
			return (Criteria) this;
		}

		public Criteria andWechatConfEqualTo(String value) {
			addCriterion("WECHAT_CONF =", value, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfNotEqualTo(String value) {
			addCriterion("WECHAT_CONF <>", value, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfGreaterThan(String value) {
			addCriterion("WECHAT_CONF >", value, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfGreaterThanOrEqualTo(String value) {
			addCriterion("WECHAT_CONF >=", value, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfLessThan(String value) {
			addCriterion("WECHAT_CONF <", value, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfLessThanOrEqualTo(String value) {
			addCriterion("WECHAT_CONF <=", value, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfLike(String value) {
			addCriterion("WECHAT_CONF like", value, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfNotLike(String value) {
			addCriterion("WECHAT_CONF not like", value, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfIn(List<String> values) {
			addCriterion("WECHAT_CONF in", values, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfNotIn(List<String> values) {
			addCriterion("WECHAT_CONF not in", values, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfBetween(String value1, String value2) {
			addCriterion("WECHAT_CONF between", value1, value2, "wechatConf");
			return (Criteria) this;
		}

		public Criteria andWechatConfNotBetween(String value1, String value2) {
			addCriterion("WECHAT_CONF not between", value1, value2, "wechatConf");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
	 * @mbg.generated  Tue Nov 28 12:49:57 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUBLIC.TWO_DIMENTION_CODE
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 28 11:26:22 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}