package com.mybatis;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.ID
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.OPEN_ID
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.NICK_NAME
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	private String nickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.EMAIL
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.AVATAR_URL
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	private String avatarUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.UPDATE_TIME
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.ID
	 * @return  the value of PUBLIC.USERS.ID
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.ID
	 * @param id  the value for PUBLIC.USERS.ID
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.OPEN_ID
	 * @return  the value of PUBLIC.USERS.OPEN_ID
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.OPEN_ID
	 * @param openId  the value for PUBLIC.USERS.OPEN_ID
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.NICK_NAME
	 * @return  the value of PUBLIC.USERS.NICK_NAME
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.NICK_NAME
	 * @param nickName  the value for PUBLIC.USERS.NICK_NAME
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.EMAIL
	 * @return  the value of PUBLIC.USERS.EMAIL
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.EMAIL
	 * @param email  the value for PUBLIC.USERS.EMAIL
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.AVATAR_URL
	 * @return  the value of PUBLIC.USERS.AVATAR_URL
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public String getAvatarUrl() {
		return avatarUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.AVATAR_URL
	 * @param avatarUrl  the value for PUBLIC.USERS.AVATAR_URL
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.UPDATE_TIME
	 * @return  the value of PUBLIC.USERS.UPDATE_TIME
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.UPDATE_TIME
	 * @param updateTime  the value for PUBLIC.USERS.UPDATE_TIME
	 * @mbg.generated  Sun Nov 26 15:15:32 CST 2017
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}