package com.mybatis;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.OPEN_ID
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.NICK_NAME
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	private String nickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.EMAIL
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.USERS.AVATOR_URL
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	private String avatorUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.OPEN_ID
	 * @return  the value of PUBLIC.USERS.OPEN_ID
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.OPEN_ID
	 * @param openId  the value for PUBLIC.USERS.OPEN_ID
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.NICK_NAME
	 * @return  the value of PUBLIC.USERS.NICK_NAME
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.NICK_NAME
	 * @param nickName  the value for PUBLIC.USERS.NICK_NAME
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.EMAIL
	 * @return  the value of PUBLIC.USERS.EMAIL
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.EMAIL
	 * @param email  the value for PUBLIC.USERS.EMAIL
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.USERS.AVATOR_URL
	 * @return  the value of PUBLIC.USERS.AVATOR_URL
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public String getAvatorUrl() {
		return avatorUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.USERS.AVATOR_URL
	 * @param avatorUrl  the value for PUBLIC.USERS.AVATOR_URL
	 * @mbg.generated  Fri Nov 24 16:52:28 CST 2017
	 */
	public void setAvatorUrl(String avatorUrl) {
		this.avatorUrl = avatorUrl;
	}
}